data_path: data
image_size: 112
mobilenet_size: large
num_landmarks: 49
patch_size: 28
feat_dim: 768
mlp_dim: 2048
num_heads: 12
num_layers: 1
dropout: 0.1
weight_decay: 0.1
T_0: 10
T_mult: 1
eta_min: 0.1
epochs: 2
batch_size: 128
lr: 0.001
